=== MidouBrihoum/Extraction-2/xml/dtdice.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT definition (abstr,concret)>
<!ATTLIST definition  attr CDATA #IMPLIED   >

<!ELEMENT abstr (keywords,types,message+,portType)>
<!ATTLIST abstr   id ID #REQUIRED>

<!ELEMENT concret (liaison)>
<!ATTLIST concret    id ID #REQUIRED>

<!ELEMENT keywords (Keyword)+>
<!ATTLIST keywords attr CDATA #IMPLIED  >

<!ELEMENT types (complexType)>
<!ATTLIST types attr CDATA #IMPLIED  >

<!ELEMENT message (part)+>
<!ATTLIST message  attr CDATA #IMPLIED   name NMTOKEN #REQUIRED>

<!ELEMENT portType (operation)+>
<!ATTLIST portType  attr CDATA #IMPLIED name  NMTOKEN #REQUIRED>

<!ELEMENT liaison (titre,application,operationC+)>
<!ATTLIST liaison  attr CDATA #IMPLIED    name NMTOKEN #REQUIRED  type NMTOKEN #REQUIRED>

<!ELEMENT Keyword (#PCDATA)>
<!ATTLIST Keyword attr CDATA #IMPLIED  >

<!ELEMENT complexType (element)+>
<!ATTLIST complexType  attr CDATA #IMPLIED   name NMTOKEN #REQUIRED>

<!ELEMENT part EMPTY>
<!ATTLIST part attr CDATA #IMPLIED    name NMTOKEN #REQUIRED type NMTOKEN #REQUIRED>

<!ELEMENT application (#PCDATA)>
<!ATTLIST application attr CDATA #IMPLIED  >

<!ELEMENT element EMPTY>
<!ATTLIST element  attr CDATA #IMPLIED    name NMTOKEN #REQUIRED  type NMTOKEN #REQUIRED>

<!ELEMENT operation ((titre,nligne)|(input,output,conditions))>
<!ATTLIST operation  attr CDATA #IMPLIED  
  name NMTOKEN #REQUIRED
  type NMTOKEN #IMPLIED>

<!ELEMENT nligne (debut,fin)>
<!ATTLIST nligne  attr CDATA #IMPLIED  >

<!ELEMENT input EMPTY>
<!ATTLIST input  attr CDATA #IMPLIED  
  message NMTOKEN #REQUIRED>

<!ELEMENT output EMPTY>
<!ATTLIST output  attr CDATA #IMPLIED  
  message NMTOKEN #REQUIRED>

<!ELEMENT conditions (Precondition?,Postcondition+)>
<!ATTLIST conditions  attr CDATA #IMPLIED  >

<!ELEMENT debut (#PCDATA)>
<!ATTLIST debut attr CDATA #IMPLIED  >

<!ELEMENT fin (#PCDATA)>
<!ATTLIST fin  attr CDATA #IMPLIED  >

<!ELEMENT Precondition (#PCDATA)>
<!ATTLIST Precondition attr CDATA #IMPLIED  
  name NMTOKEN #REQUIRED>

<!ELEMENT Postcondition (#PCDATA)>
<!ATTLIST Postcondition  attr CDATA #IMPLIED  
  name NMTOKEN #REQUIRED>

<!ELEMENT titre (#PCDATA)>
<!ATTLIST titre  attr CDATA #IMPLIED  >

=== MidouBrihoum/Extraction-2/xml/ICE_service_03.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE definition SYSTEM "dtdice.dtd"><definition><abstr id="abstract">  <keywords>  <Keyword>arythmetique</Keyword>   <Keyword>division</Keyword>  <Keyword>addition</Keyword>  <Keyword>calcul</Keyword>   <Keyword>mathematique</Keyword>  <Keyword>/</Keyword> </keywords>      <types>     <complexType name="div">           <element name="A" type="int"/>           <element name="B" type="int"/>                      </complexType>            </types>  <message name="entree">    <part name="in" type="int"/>        <part name="in2" type="int"/>      </message> <message name="entree3">    <part name="in" type="int"/>        <part name="in2" type="int"/>  </message>   <message name="sortie">    <part name="out" type="int"/>        <part name="out2" type="int"/>      </message>  <message name="sortie3">    <part name="out" type="int"/>        <part name="out2" type="int"/>  </message>    <operations name="Arythmetique">    <operation name="Division">     <input message="entree"/>     <output message="sortie"/>    <conditions>    <Precondition name="div_zero" > tricou dpou </Precondition>    <Postcondition name="post1" > une poste condition 1  </Postcondition>    <Postcondition name="post11" > une poste condition 11  </Postcondition>            <Postcondition name="post13" > une poste condition 3  </Postcondition>        </conditions>        </operation>            <operation name="Addition">     <input message="entree3"/>     <output message="sortie3"/>    <conditions>    <Postcondition name="post1" > une poste condition 1  </Postcondition>    <Postcondition name="post11" > une poste condition 11  </Postcondition>        </conditions>        </operation>         </operations></abstr> <concret id="concret"><liaison name="binding_arythmetique" type="Arythmetique">  <titre>Mathematique</titre>     <application> Calculatrice </application>    <operationC name="division" type="Function" >      <titre >division() </titre>       <nligne>        <debut> 145 </debut>        <fin> 161 </fin>      </nligne>    </operationC>    <operationC name="Addition" type="Function" >      <titre >Addition() </titre>       <nligne>        <debut> 164 </debut>        <fin> 186 </fin>      </nligne>    </operationC>  </liaison></concret></definition>

=== MidouBrihoum/Extraction-2/xml/ICE_service_02.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE definition SYSTEM "dtdice.dtd"><definition>  <abstr id="abstract">    <keywords>  <Keyword>arythmetique</Keyword>   <Keyword>soustraction</Keyword>  <Keyword>addition</Keyword>  <Keyword>calcul</Keyword>   <Keyword>mathematiqu-</Keyword>  <Keyword>-</Keyword>  <Keyword>+</Keyword> </keywords>      <types>     <complexType name="Comp">           <element name="A" type="int"/>           <element name="B" type="int"/>                      </complexType>            </types>  <message name="entree3">    <part name="in" type="int"/>        <part name="in2" type="int"/>      </message> <message name="entree4">    <part name="in_devision" type="double"/>        <part name="in_devision2" type="double"/>      </message>   <message name="sortie3">    <part name="out" type="int"/>        <part name="out2" type="int"/>      </message>  <message name="sortie4">    <part name="outtestetion" type="double"/>        <part name="out2testation" type="float"/>      </message>    <portType name="Arythmetique">    <operation name="Addition">     <input message="entree3"/>     <output message="sortie3"/>    <conditions>    <Postcondition name="post1" > une poste condition 1  </Postcondition>    <Postcondition name="post11" > une poste condition 11  </Postcondition>        </conditions>        </operation>        <operation name="Soustraction">     <input message="entree4"/>     <output message="sortie4"/>    <conditions> <Postcondition name="post6" > une poste condition 2  </Postcondition>    </conditions>        </operation>         </portType></abstr> <concret id="concret"><liaison name="binding_arythmetique" type="Arythmetique">  <titre>Mathematique</titre>     <application> Calculatrice </application>    <operationC name="Soustraction" type="Function" >      <titre >soustraction() </titre>       <nligne>        <debut> 145 </debut>        <fin> 161 </fin>      </nligne>    </operationC>    <operationC name="Addition" type="Function" >      <titre >Addition() </titre>       <nligne>        <debut> 164 </debut>        <fin> 186 </fin>      </nligne>    </operationC>  </liaison></concret></definition>
