=== MidouBrihoum/Extraction-2/xml/dtdprest.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Prestataires (Prestataire)+>
<!ATTLIST Prestataires
  xmlns CDATA >

<!ELEMENT Prestataire (name,adresse,description)>
<!ATTLIST Prestataire
  xmlns CDATA 
  id ID #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  xmlns CDATA >

<!ELEMENT adresse (#PCDATA)>
<!ATTLIST adresse
  xmlns CDATA >

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
  xmlns CDATA >

=== MidouBrihoum/Extraction-2/xml/prestataires.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE definition SYSTEM "dtdprest.dtd"><Prestataires > <Prestataire id="Entreprise_01">	<name> PMO </name> 	<adresse> El khroub - constantine </adresse>	<description> Production machine outils</description></Prestataire><Prestataire id="Entreprise_02"><name> SEACO </name> <adresse> constantine </adresse><description> distribution d'eau</description></Prestataire></Prestataires>
